name: AWSomeCreds CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run unit tests
      run: make test

  integration-test:
    runs-on: ubuntu-latest
    # Only run integration tests on specific branches or when manually triggered
    # Remove this 'if' condition if you want to run integration tests on all pushes/PRs
    if: github.event_name == 'workflow_dispatch' || contains(github.ref, 'integration')
    needs: test
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Get dependencies
      run: go mod download

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Run integration tests
      env:
        TEST_ROLE_ARN: ${{ secrets.TEST_ROLE_ARN }}
        TEST_SOURCE_PROFILE: ${{ secrets.TEST_SOURCE_PROFILE }}
        TEST_REGION: ${{ secrets.AWS_REGION }}
        RUN_INTEGRATION_TESTS: "1"
      run: go test -v ./... 